### ISSUE TITLE
include msw?

### ISSUE THREAD

**Issue by ranielzed** [davipon/svelte-component-test-recipes#1]
Thanks for setting this up! This is very helpful and encourages testing for more reliable code. Though I'm not sure if this is in scope but it would be nice if there's also a recipe for setting up msw for components that fetch data

**Comment by davipon** [comment]
@ranielzed I'm glad it's helpful!

That's a good idea and I'd love to add it.
I did have an `msw` example in another repo [svelte-add-vitest](https://github.com/davipon/svelte-add-vitest) but it lacks explanation.

Kindly let me know if you have any good examples or ideas to demonstrate in this repo.

**Comment by davipon** [comment]
@ranielzed I added `msw` examples for internal and external fetch calls.
