### ISSUE TITLE
c8 vs @vitest/coverage-c8

### ISSUE THREAD

**Issue by SaschaLucius** [davipon/svelte-component-test-recipes#19]
Hey,
if I'm looking at your dependencies, I've faced that you are using c8 directly.
On vitest documentation page (https://vitest.dev/guide/coverage.html) I've found the reference to  @vitest/coverage-c8.
Do you know if there is any difference, or reason to choose one in favor of the other?

**Comment by davipon** [comment]
I overlooked the `@vitest/coverage-c8` package. It was added after vitest v0.22.
PR #20 to replace `c8`.

**Comment by SaschaLucius** [comment]
Thank you, this clarifies my question
