### ISSUE TITLE
Internal / External Fetch using Axios instead of Fetch

### ISSUE THREAD

**Issue by Skylli202** [davipon/svelte-component-test-recipes#61]
Hi,

Firstly, thanks for your awesome work @davipon.  
This issue is more a question than a real repo issue. I hope you don't mind that.

I'd like to know why, in your Internal / External fetch examples, you choose to use `Axios`. Well-known deps for sure, but in all the Svelte documentation (Svelte & SvelteKit docs) they always show us the native `fetch` function. 

Thanks in advance for your answer.

**Comment by davipon** [comment]
Hi @Skylli202, it was a historical reason that `msw` didn't support native Node.js 18 `fetch`: https://github.com/mswjs/msw/issues/1388.

While it seems `msw` supports now, you could give it a try.

**Comment by Skylli202** [comment]
Thanks a lot for your quick answer. This is not related, but I'd like to inform you that `svelte-htm` and `svelte-fragment-component` are not been updated (yet? idk if they are still maintained) for Svelte 4.0.

Would you accept a PR who just add a warning at the start of the `README.md` ?

**Comment by davipon** [comment]
Yeah sure! PR is welcome.

 I haven't worked on a Svelte project professionally for half a year, I believe those packages might not be an ideal solution now. 
Maybe there is a better way to do component test in Svelte 4 or 5.
